[build]
  command = "npm run build && npm run inject-env"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning completely
  SECRETS_SCAN_ENABLED = "false"
  # Do NOT hardcode actual keys here - set these in Netlify UI
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

# Post processing command to replace environment variables in the client JS files
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Update CSP to allow inline styles and Supabase
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co; img-src 'self' data: https://*.supabase.co https://*.unsplash.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache settings for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add environment context settings
[context.production]
  environment = { NODE_VERSION = "18" }
  
[context.deploy-preview]
  environment = { NODE_VERSION = "18" }
  
[context.branch-deploy]
  environment = { NODE_VERSION = "18" }

# Handle SPA routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Country = ["*"]} 