[build]
  command = "npm run build"
  publish = ".next"

# Disable secrets scanning or configure omissions
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  # Disable secrets scanning completely - use this if you're handling secrets properly
  SECRETS_SCAN_ENABLED = "false"
  # Alternative: Omit specific keys from scanning
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,OPENAI_API_KEY"

# Define redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Explicitly include JavaScript files from the public directory
[[headers]]
  for = "/pre-init.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/gotrue-patch.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/env.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Handle Supabase content security policy and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://ipv4.icanhazip.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*.supabase.co https://images.unsplash.com; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Access-Control-Allow-Origin = "*"

# For Supabase images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# For Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle Netlify Functions/Edge Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "next"
  targetPort = 3000

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false 