[build]
  command = "npm run build"
  publish = "out"
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inject-env"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://cpzzmpgbyzcqbwkaaqdy.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwenptcGdieXpjcWJ3a2FhcWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDcwMDEsImV4cCI6MjA1OTUyMzAwMX0.7QCxICVm1H7OmW_6OJ16-7YfyR6cYCfmb5qiCcUUYQw"
  # Disable secrets scanning completely
  SECRETS_SCAN_ENABLED = "false"

# Post processing command to replace environment variables in the client JS files
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Update CSP to allow inline styles and Supabase
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co; img-src 'self' data: https://*.supabase.co https://*.unsplash.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache settings for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add environment context settings
[context.production]
  environment = { NODE_VERSION = "18" }
  
[context.deploy-preview]
  environment = { NODE_VERSION = "18" }
  
[context.branch-deploy]
  environment = { NODE_VERSION = "18" }

# Handle SPA routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Country = ["*"]} 