[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning completely
  SECRETS_SCAN_ENABLED = "false"

# Post processing command to replace environment variables in the client JS files
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false

# Add environment variables to the HTML
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Add Content-Security-Policy header to allow inline scripts
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co; img-src 'self' data: https://*.supabase.co;"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add post-processing script to inject environment variables into the HTML
[context.production]
  environment = { NODE_VERSION = "18" }
  
[context.deploy-preview]
  environment = { NODE_VERSION = "18" }
  
[context.branch-deploy]
  environment = { NODE_VERSION = "18" } 